sites:
  - name: "The Hacker News"
    base_url: "https://thehackernews.com/"
    article_selector: "div.body-post.clear"
    title_selector: "h2.home-title"
    desc_selector: "div.home-desc"
    date_selector: "span.h-datetime"
  - name: "Cyber Security News"
    base_url: "https://cybersecuritynews.com/"
    article_selector: "div.td-block-span12"
    title_selector: "h3.entry-title.td-module-title"
    desc_selector: "div.td-excerpt"
    date_selector: "time.entry-date"
  - name: "BBC News"
    base_url: "https://www.bbc.com/news/topics/cz4pr2gd85qt"
    article_selector: "div[data-testid='liverpool-card']"
    title_selector: "h2[data-testid='card-headline']"
    desc_selector: "p[data-testid='card-description']"
    date_selector: "span[data-testid='card-metadata-lastupdated']"